### ISSUE TITLE
Authorization mechanism not supported (please use AWS4-HMAC-SHA256) [0.9.5.1]

### ISSUE THREAD

**Issue by flerro** [szepeviktor/fix-w3tc#192] opened 2016-12-10 20:55 UTC
Hello,

Thanks for the great effort of mantaining this fork.

I have an AWS S3 bucket hosted on eu-central-1 and I experienced a problem using the plugin with that bucket. When I test the upload I get the following error: 

```Error: Unable to put object (S3::putObject(): [InvalidRequest] The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.).```

I have no problem uploading to the same S3 bucket via the AWS cli using the same IAM user.

![screenshot from 2016-12-10 20-10-37](https://cloud.githubusercontent.com/assets/593048/21076061/44c798dc-bf22-11e6-8adf-70a2ca85fe73.png)

May you please help me?

Thanks,
Francesco

**Comment by amiga-500** [comment] 2016-12-11 04:08
Hi @flerro ... the problem is that the _eu-central-1_ region only supports AWS signature version 4 only.  Most of the other regions support both version 2 and version 4.  As you can guess, w3tc only handles version 2.  It seems _eu-west-1_ supports both v2 and v4.  So if you had a bucket that was associated with that region instead w3tc would pass when you click the <kbd>Test S3 Upload</kbd> button.

I will look to add version 4 support soon.  

Cheers
Kimberly

**Comment by amiga-500** [comment] 2016-12-16 20:53
@flerro - I've officially added (and tested) v4 signature support (aka the fix for the _AWS4-HMAC-SHA256_ error) into fix-w3tc.  It's currently in the v0.9.4x generation only, but adding it also to the v0.9.5.x generation should be straight forward.  I've added more regions/endpoints to select from (total: 14) too. 

I haven't committed this update just yet to the branch.  I am doing other updates and so will just push it with the others as one lump update in a few days.  

Just wanted to let you know in case you were interested in how things are progressing.

Kimberly

**Closed** 2016-12-16 21:00 UTC
