### ISSUE TITLE
Incorrectly removes ?ver= parameter from CSS styles and scripts

### ISSUE THREAD

**Issue by archon810** [szepeviktor/fix-w3tc#379] opened 2017-02-13 21:58 UTC
Originally reported here https://wordpress.org/support/topic/w3-total-cache-incorrectly-removes-ver-parameter-from-css-styles-and-scripts, but someone pointed out this repo and suggested I file it here too.

The problem occurs when in W3TC settings -> Browser cache -> CSS/JS -> “Prevent caching of objects after settings change” is turned on. Instead of appending the ?xNNNN cache bust value to the urls, it incorrectly overrides and erases the ?ver= parameter entirely.

For example,
```html
<script type='text/javascript' src='http://SITE/wp-content/themes/THEME/js/example.js?ver=4.7.2'></script>
```
becomes
```html
<script type='text/javascript' src='http://SITE/wp-content/themes/THEME/js/example.js?x41610'></script>
```
instead of
```html
<script type='text/javascript' src='http://SITE/wp-content/themes/THEME/js/example.js?ver=4.7.2&x41610'></script>
```

This means that the cache will only be busted when new W3TC settings are saved rather than when the WP version or file version changes.

The bug in W3TC 0.9.5.2 is here:
```php
$test_url = Util_Environment::remove_query( $url ); 
```
on line 215 of BrowserCache_Plugin.php
In turn:
```php
static public function remove_query( $url ) {
  $url = preg_replace( '~[&\?]+(ver=([a-z0-9-_\.]+|[0-9-]+))~i', '', $url );
return $url;
}
```
is on line 837 of Util_Environment.php.

As you can see, it empties out ver= for some reason, which is incorrect behavior.

Can we hope for a fix? I’d like to keep this setting enabled, but for now I’m forced to turn it off.

**Comment by amiga-500** [comment] 2017-02-13 23:50
Thanks a bunch for the details @archon810 (luv your name! reminds me of an old game).  I will play around so i can see the problem first-hand.  I want to snoop around other related areas even more.  I should be able to have a fix added in later today after i'm satisfied.

Cheers
Kimberly :octocat:

**Comment by archon810** [comment] 2017-02-14 00:09
That's awesome. I wish W3TC devs were this responsive.

I have a feeling the ver= cleaning function may be used elsewhere and has its own uses, so tread carefully.

Cheers.

**Comment by amiga-500** [comment] 2017-02-14 02:03
Hi again @archon810 ... the problem is caused specifically by [line **182**](https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/BrowserCache_Plugin.php#L182) in _BrowserCache_Plugin.php_ (inside the `mutate_url()` function).  This line shouldn't be there:

```php
$url = Util_Environment::remove_query( $url );
```
When its removed (or commented out) your problem is fixed.

I'm still roaming the code (and analyzing the front end) but I just wanted to share this with you in case u needed the problem fixed asap.  From what i can see this problem would only occur for query strings that begin with `?ver=xxx` ... if it were say `?foo=xxx` the same problem wouldn't occur.  So again, i get a sense that, that aforementioned line shouldnt be there.  After i do s'more tests i'll hopefully be committing this as a fix.

Kimberly :octocat:

**Comment by archon810** [comment] 2017-02-14 04:37
Hi @amiga-500, indeed, it only removes ver=, the other parameters survive. 

I wish the original developers responded more frequently so that they can at least say if there's a reason they did it this way.

**Comment by amiga-500** [comment] 2017-02-14 06:19
@archon810  ... after doing some hunting around i found the `remove_query()` isn't used that much in this plugin.  Interestingly, two other places in code (not related to your problem) are actually using it wrong (they should be using `remove_query_all()` instead -- i'll be taking care of that later).

The sole purpose of `remove_query()` as you already know is to remove the wp appended _?ver=xxx_.  But if the url has other query name-value pairs they would be preserved which leads me to believe having a function to remove this version is just there for the sake of ridding a visual nuisance.  I can understand why it's removed when using Minification on JS/CSS (which btw still performs exactly how it should after this fix) but outside that i see no practical reason the version is removed when the function is used.  Again, in some cases when he did use `remove_query()`, it's actually used incorrectly (e.g. under _ObjectCache_Environment.php_).

So anyway, i am pretty confident my proposal above is correct for your problem.  It all seems to work well (i simulated your case) in my tests.

Regards
Kimberly

**Comment by twiginteractive** [comment] 2017-02-14 18:16
Amazing - I was about to report this same issue and @archon810 has already done so, and admirably! I like the force QS option but noticed it mangles asset URLs to be ...?XXXX?ver=4.7.2 instead of ?XXX&ver=4.7.2

Could this fix be applied to the 0.9.4.x branch too (when it gets to be deployed)?

Great responsiveness as always from @amiga-500

**Comment by amiga-500** [comment] 2017-02-14 20:33
Hi @twiginteractive ... welcome back!  Got some questions for ya.  

1. Is this problem occurring when you too have _Browser Cache_ enabled with "_Prevent caching of objects after settings change_" checked?  So this problem only occurs when those are enabled?

2. Is the **?XXXX** you mention the unique identifier added by w3tc e.g. **a7ac6c** as in **?a7ac6c?ver=4.7.2**

3. If its not too complex can you give the steps on how you get this problem?  I want to recreate it on my end. 

Thanks

**Comment by archon810** [comment] 2017-02-14 20:37
@amiga-500 Your responsiveness continues to be amazing.

Side question: Do you have a professional listing somewhere (LinkedIn?) or another method (Hangouts, Telegram, etc) where I can contact you privately?

**Comment by amiga-500** [comment] 2017-02-14 20:38
@archon810 sadly none yet.  I will get to it eventually :stuck_out_tongue_winking_eye:

**Comment by archon810** [comment] 2017-02-14 20:38
As for the fix to this issue, I guess we'll have to wait for @twiginteractive's response to make sure it covers their case too, right @amiga-500?

**Comment by archon810** [comment] 2017-02-14 20:39
@amiga-500 OK, I'd love to hear about your work experience and have a possible gig for you. Sadly, Github does not allow private messaging. Can we have a brief chat?

**Comment by amiga-500** [comment] 2017-02-14 20:40
@archon810 when i think about it more i get a sense his problem might actually be different from yours.  But i am curious to see how the problem occurs so i can see if it also affects the 0.9.5.x generation users like yourself too.  He is a 0.9.4.x branch user.  0.9.4.x underlying coding is different and so operates differently than 0.9.5.x in ways.

**Comment by twiginteractive** [comment] 2017-02-14 20:44
@amiga-500 Yup! You have it exactly right.

I enqueue an asset in WP per best-practice, and it appends "?ver=X.X" to them. Great. Then I turn on the option in Browser Cache as you mention (I'm running the 0.9.4.x branch but I think it's the same for 0.9.5.x)

Corresponding URL becomes ...?a7ac6c?ver=4.7.2 etc.
I also use S3 CDN, but I don't that is required to display this issue.

If you'd like, I can easily spin up a new clean WP install and verify. To be clear, it's not an issue in that hte asset doesn't load (it DOES load) but the versioning becomes tough to control: i.e. if I modify the version number (which I do for logged-in users) the current URL format ignores my ver variable because the URL is malformed.

Also @archon810 - it's little different in that cache-buster doesn't REMOVE my ver=xxx but it does invalidate it because ?...? is a malformed querystring

**Comment by twiginteractive** [comment] 2017-02-14 20:47
Also @amiga-500 - please add me to the announcement distro list once you get your LinkedIn profile set up!

**Comment by amiga-500** [comment] 2017-02-14 21:14
Hi again @twiginteractive  ...great i see the problem now.... ok it's specific to the 0.9.4.x branch only and only when CDN is enabled.  

When CDN isn't enabled then it acts like 0.9.5.x where it strips the ?ver (when the "_Prevent caching of objects._." is checked on) .  So i'll add the fix way above to resolve that similar problem in 094x too ( i just have to figure out where that is since the coding is very different).  But for the CDN issue i will have to explore s'more  what is causing it ... I will finish things up for this 0.9.5.x issue and then focus my attention on your CDN _?ver_ issue.

Thanks for the feedback and  I will let you know when i have the fix so u can test it on your end.

Cheers
Kimberly

**Comment by amiga-500** [comment] 2017-02-15 00:06
Hi again @archon810 ... just an update ... i finally committed the v095x fix.  For your convenience here are those changed files:

**[BrowserCache_Plugin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/BrowserCache_Plugin.php)**
[DbCache_Environment.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/DbCache_Environment.php)
[ObjectCache_Environment.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/ObjectCache_Environment.php)
[lib/Minify/Minify/CSS/UriRewriter.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/lib/Minify/Minify/CSS/UriRewriter.php)
[Util_Environment.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/Util_Environment.php)

The one that relates to your problem is the fix in _BrowserCache_Plugin.php_ the rest are just tweaks and other indirect bug patches i made that don't necessarily relate to your issue but figured i should probably include them here too.

If your problem persists just let me know (include info on how to recreate it).

Regards
Kimberly :octocat:

**Comment by archon810** [comment] 2017-02-15 00:42
@amiga-500 Thanks, I'm still trying to decide whether to use the official plugin or this community version. Either way, I'll wait for a release/tag rather than going for the branch's master.

O/T: Sent you an email to misc905+github@gmail.com, I hope that's a valid email.

**Comment by amiga-500** [comment] 2017-02-15 00:46
Not a problem!  Yea good idea to wait for an official release!  The author routinely visits this repository and then incorporates the fixes and updates that we put in.  So there is a good chance that his next release will have these changes.  Hopefully he will make an official release in a month or two and that will be that.

Cheers
Kimberly :octocat:

**Closed as completed by amiga-500** 2017-02-15 00:46 UTC
Labels: Feature Request, 0.9.5.x

**Comment by archon810** [comment] 2017-02-21 00:13
@amiga-500 Any idea when your own official release is going to be?
