### ISSUE TITLE
Status: not cached on normal url when option to cache url with query strings is enabled

### ISSUE THREAD

**Issue by MaciejKrawczyk** [szepeviktor/fix-w3tc#113] opened 2016-09-26 09:33 UTC
Hello. I think I've found another bug with caching exceptions. When the option to cache url with query strings is disabled, everything is ok. URLs without query strings are cached, ones with query strings are not:
```
Page without query:
Caching:            enabled
Status:             cached

Page with query:
Caching:            disabled
Reject reason:      Requested URI contains query
Status:             not cached
```

However, with the option to cache urls with query strings enabled, the results are:
```
Page without query:
Caching:            enabled
Status:             not cached

Page with query:
Caching:            enabled
Status:             cached
```

Note that caching is enabled, but status is not cached, which is strange. I don't know if it is just a debug error - pages are loading fast even when status is not cached and they seem to get cached. But I'm not sure if everything is ok.

By the way, in the second case, "page with query" is not just any page with a query. The query must have an effect on rendered content. But in the first case, any query will do to be treated as a page with query and be rejected from caching.

**Comment by MaciejKrawczyk** [comment] 2016-09-26 11:25
It is something acpu related. I switched to disk enhanced, but then the option to cache pages with queries is disabled. Anyway it's not that necessary for me to cache pages with queries and disk enhanced seems to perform better than acpu on my vps.

**Comment by amiga-500** [comment] 2016-09-27 01:46
Sorry for the delay.  Have you moved on to using the official 0.9.5 release (on WP.org)?  Delayed looking into this because Frederick (w3tc author) has finally risen from the dead.  But, for the sake of consistency ill have a look into this issue later tonight.  Thanks again for the heads up!

**Comment by amiga-500** [comment] 2016-09-27 05:42
So to be clear...this all works fine when in _Disk: Basic_ mode (since cache queries checkbox is available but disabled under Disk Enhanced).  However, in APCu mode only the problem happens?

**Comment by amiga-500** [comment] 2016-09-27 07:07
### Update
I did some tests with APCu and it seems this is not a bug....let me explain:

When you see:
```
Caching:    enabled
Status:     not cached
```
it indicates that a cache entry doesnt currently exist and one is going to be generated (to be used for subsequent requests to that page).  In other words, someone is calling a page for the first time (or it has an old cache file) and a new cache needs to be generated and written out.  So "_not cached_" is an indication that this page doesn't currently have a cache entry but since there is a "_caching:enabled_", a new cache file is being generated.  This is explains why when you looked, despite seeing "not cached", that you saw it was indeed cached.

And so, that leads us to this:
```
Caching:    enabled
Status:     cached
```
This indicates that a cache entry does exist (and hasn't expired yet) and is currently being served back to the client browser.

Not sure if your cached entries are repeatedly showing _"not cached_" for pages that were cached moments earlier.  If so then i wonder about your APCu settings in that i know there is a feature that flushes the entire memory after a certain interval and if that interval time is set very low.

So for now i will Close this thread, but if you think i am wrong please feel free to re-open it.  More than happy to assist.

**Closed by amiga-500** 2016-09-27 07:07 UTC
