### ISSUE TITLE
Inconsistent object cache result and flushing

### ISSUE THREAD

**Issue by deltafactory** [szepeviktor/fix-w3tc#402] opened 2017-02-20 22:16 UTC
The environment is PHP7, W3TC-fixed 0.9.4.6.3, WP 4.7.2 and AWS Elasticache's Memcache 1.4.33. Page caching and cache headers (max-age) are forcing page loads from the server every time.

I have had 2 different cases where I was seeing old and new contents of the object cache. Emptying All and Object Cache multiple times had no effect.

I used a separate utility to send a flush_all command to the Memcache server which immediately fixed the issue. I understand that W3TC's object cache increments the group key value but this low-level flush was my last resort.

**Comment by nigrosimone** [comment] 2017-02-25 08:34
@deltafactory same as https://github.com/szepeviktor/w3-total-cache-fixed/issues/416 i suggest you to [upgrade to 0.9.5.x](https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog) (_i have upgrade all my website without any issues_). 

Honestly we are just a bit of developers and the most active is in a long pause. I have a bit of time for this project and manage two branch is inapplicable, mostly if the issue is time-expensive to reproduce and in this case i need a AWS Elasticache service, because "page cache" with pure Memcache seems works (_maybe, is the problem AWS Elasticache? too much work for try it_).

**Try to upgrade, and if the issue persists, i'm happy to try to fix it on 0.9.5.x's branch.**

We have ported all 0.9.4.x's features and fixes in the 0.9.5.x's branch, the only one reason for avoid update is that: 0.9.5.x need a php >= 5.3

Always thanks.

**Comment by nigrosimone** [comment] 2017-02-25 15:59
@deltafactory feel free to reopen, i close it just because in the https://github.com/szepeviktor/w3-total-cache-fixed/issues/416 you have choise to upgrade at 0.9.5.x.

**Closed as completed by nigrosimone** 2017-02-25 15:59 UTC
Labels: 0.9.4.x, Needs investigation
